# Generated by Django 6.1 on 2026-08-29 08:01

import apps.debates.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Debate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic", models.TextField()),
                (
                    "join_code",
                    models.CharField(
                        db_index=True,
                        default=apps.debates.models.generate_join_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lobby", "Lobby"),
                            ("active", "Active"),
                            ("voting", "Voting"),
                            ("closed", "Closed"),
                        ],
                        default="lobby",
                        max_length=16,
                    ),
                ),
                (
                    "current_side",
                    models.CharField(
                        choices=[("team_a", "Team A"), ("team_b", "Team B")],
                        default="team_a",
                        max_length=16,
                    ),
                ),
                ("current_round", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=40)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("moderator", "Moderator"),
                            ("team_a", "Team A"),
                            ("team_b", "Team B"),
                            ("audience", "Audience"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=apps.debates.models.generate_token,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "debate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="debates.debate",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Argument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("team_a", "Team A"), ("team_b", "Team B")],
                        max_length=16,
                    ),
                ),
                ("round_number", models.PositiveIntegerField()),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "debate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arguments",
                        to="debates.debate",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="debates.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("debate", "side", "round_number"),
                        name="one_argument_per_side_per_round",
                    )
                ],
            },
        ),
    ]
